---
title: "Alice Chonga – International HR Strategist"
description: "Global HR for a Changing World"
baseurl: "" # keep empty for GitHub Pages project site
url: "https://alicechonga.com/openai"

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
